# 1)Scrape the details of most viewed videos on YouTube from Wikipedia:
### Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
### You need to find following details:
#### A) Rank
#### B) Name
#### C) Artist
#### D) Upload date
#### E) Views

In [181]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importing time
import time

In [182]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [183]:
# Opening the homepage
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [184]:
# making empty lists
rank=[]
name=[]
artist=[]
views=[]
upload_date=[]

In [153]:
# Extracting data from xpath
lists=[]
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td"):
    lists.append(i.text)
lists=lists[:180]
lists

['1.',
 '"Baby Shark Dance"[22]',
 "Pinkfong Kids' Songs & Stories",
 '9.06',
 'June 17, 2016',
 '[B]',
 '2.',
 '"Despacito"[24]',
 'Luis Fonsi',
 '7.47',
 'January 12, 2017',
 '[C]',
 '3.',
 '"Johny Johny Yes Papa"[25]',
 'LooLoo Kids',
 '5.60',
 'October 8, 2016',
 '[D]',
 '4.',
 '"Shape of You"[26]',
 'Ed Sheeran',
 '5.40',
 'January 30, 2017',
 '[E]',
 '5.',
 '"See You Again"[27]',
 'Wiz Khalifa',
 '5.20',
 'April 6, 2015',
 '[F]',
 '6.',
 '"Masha and the Bear – Recipe for Disaster"[30]',
 'Get Movies',
 '4.45',
 'January 31, 2012',
 '[G]',
 '7.',
 '"Bath Song"[31]',
 'Cocomelon – Nursery Rhymes',
 '4.39',
 'May 2, 2018',
 '[H]',
 '8.',
 '"Learning Colors – Colorful Eggs on a Farm"[32]',
 'Miroshka TV',
 '4.35',
 'February 27, 2018',
 '[I]',
 '9.',
 '"Uptown Funk"[33]',
 'Mark Ronson',
 '4.25',
 'November 19, 2014',
 '[J]',
 '10.',
 '"Gangnam Style"[34]',
 'Psy',
 '4.14',
 'July 15, 2012',
 '[K]',
 '11.',
 '"Phonics Song with Two Words"[36]',
 'ChuChu TV',
 '4.04',
 'March 6, 2014',
 '',
 '12.',
 '"Sugar"[37]',
 'Maroon 5',
 '3.52',
 'January 14, 2015',
 '',
 '13.',
 '"Dame Tu Cosita"[38]',
 'El Chombo',
 '3.49',
 'April 5, 2018',
 '',
 '14.',
 '"Sorry"[39]',
 'Justin Bieber',
 '3.45',
 'October 22, 2015',
 '',
 '15.',
 '"Roar"[40]',
 'Katy Perry',
 '3.40',
 'September 5, 2013',
 '',
 '16.',
 '"Counting Stars"[41]',
 'OneRepublic',
 '3.35',
 'May 31, 2013',
 '',
 '17.',
 '"Thinking Out Loud"[42]',
 'Ed Sheeran',
 '3.30',
 'October 7, 2014',
 '',
 '18.',
 '"Wheels on the Bus"[43]',
 'Cocomelon – Nursery Rhymes',
 '3.20',
 'May 24, 2018',
 '',
 '19.',
 '"Dark Horse"[44]',
 'Katy Perry',
 '3.11',
 'February 20, 2014',
 '',
 '20.',
 '"Faded"[45]',
 'Alan Walker',
 '3.11',
 'December 3, 2015',
 '',
 '21.',
 '"Girls Like You"[46]',
 'Maroon 5',
 '3.08',
 'May 31, 2018',
 '',
 '22.',
 '"Shake It Off"[47]',
 'Taylor Swift',
 '3.08',
 'August 18, 2014',
 '',
 '23.',
 '"Lean On"[48]',
 'Major Lazer',
 '3.07',
 'March 22, 2015',
 '',
 '24.',
 '"Bailando"[49]',
 'Enrique Iglesias',
 '3.07',
 'April 11, 2014',
 '',
 '25.',
 '"Let Her Go"[50]',
 'Passenger',
 '3.04',
 'July 25, 2012',
 '',
 '26.',
 '"Mi Gente"[51]',
 'J Balvin',
 '2.95',
 'June 29, 2017',
 '',
 '27.',
 '"Perfect"[52]',
 'Ed Sheeran',
 '2.91',
 'November 9, 2017',
 '',
 '28.',
 '"Axel F"[53]',
 'Crazy Frog',
 '2.91',
 'June 16, 2009',
 '',
 '29.',
 '"Waka Waka (This Time for Africa)"[54]',
 'Shakira',
 '2.90',
 'June 4, 2010',
 '',
 '30.',
 '"Hello"[55]',
 'Adele',
 '2.86',
 'October 22, 2015',
 '',
 '"Baby Shark Dance"[22]',
 "Pinkfong! Kids' Songs & Stories",
 '7,037,500,000',
 'June 17, 2016',
 'November 2, 2020',
 '275',
 '',
 '',
 '"Despacito"[24]',
 'Luis Fonsi',
 '2,993,700,000',
 'January 12, 2017',
 'August 4, 2017',
 '1,186',
 '[119]',
 '[P]',
 '"See You Again"[27]',
 'Wiz Khalifa',
 '2,894,000,000',
 'April 6, 2015',
 'July 10, 2017',
 '25',
 '[28]',
 '',
 '"Gangnam Style"⁂[34]',
 'Psy',
 '803,700,000',
 'July 15, 2012',
 'November 24, 2012',
 '1,689',
 '[35]',
 '[Q]',
 '"Baby"*[85]',
 'Justin Bieber',
 '245,400,000',
 'February 19, 2010',
 'July 16, 2010',
 '862',
 '[120]',
 '[R]',
 '"Bad Romance"[82]',
 'Lady Gaga',
 '178,400,000',
 'November 24, 2009',
 'April 14, 2010',
 '93',
 '[123]',
 '[S]',
 '"Charlie Bit My Finger"‡[73]',
 'HDCYT',
 '128,900,000',
 'May 22, 2007',
 'October 25, 2009',
 '171',
 '[126]',
 '',
 '"Evolution of Dance"[66]',
 'Judson Laipply',
 '118,900,000',
 'April 6, 2006',
 'May 2, 2009',
 '176',
 '[127]',
 '',
 '"Girlfriend"‡[128][129]',
 'RCA Records',
 '92,600,000',
 'February 27, 2007',
 'July 17, 2008',
 '289',
 '[130]',
 '',
 '"Evolution of Dance"[66]',
 'Judson Laipply',
 '78,400,000',
 'April 6, 2006',
 'March 15, 2008',
 '124',
 '[131]',
 '',
 '"Music Is My Hot Hot Sex"‡[132]',
 'CLARUSBARTEL72',
 '76,600,000',
 'April 9, 2007',
 'March 1, 2008',
 '14',
 '[133]',
 '[T]',
 '"Evolution of Dance"*[66]',
 'Judson Laipply',
 '10,600,000',
 'April 6, 2006',
 'May 19, 2006',
 '652',
 '[136]',
 '[U]',
 '"Pokemon Theme Music Video"‡[137]',
 'Smosh',
 '4,300,000',
 'November 28, 2005',
 'March 12, 2006',
 '68',
 '[138]',
 '[V]',
 '"Myspace – The Movie"‡[141][142]',
 'eggtea',
 '2,700,000',
 'January 31, 2006',
 'February 18, 2006',
 '22',
 '[143]',
 '',
 '"Phony Photo Booth"‡[144]',
 'mugenized',
 '3,400,000',
 'December 1, 2005',
 'January 21, 2006',
 '28',
 '[145]',
 '[W]',
 '"The Chronic of Narnia Rap"‡[146]',
 'youtubedude',
 '2,300,000',
 'December 18, 2005',
 'January 9, 2006',
 '12',
 '[147]',
 '',
 '"Ronaldinho: Touch of Gold"‡*[148]',
 'Nikesoccer',
 '255,000',
 'October 21, 2005',
 'October 31, 2005',
 '70',
 '[149]',
 '[X]',
 '"I/O Brush"‡*[151]',
 'larfus',
 '247,000',
 'October 5, 2005',
 'October 29, 2005',
 '2',
 '[152]',
 '',
 '"Me at the zoo"[57]',
 'jawed',
 '1',
 'April 23, 2005',
 'April 23, 2005',
 '1',
 '[153]',
 '']

In [185]:
# Extracting rank,name,artist,views,upload from list
r=lists[0::3]
rank=r[::2]
views=r[1::2]

t=lists[1::3]
video_name=t[0::2]
upload_date=t[1::2]

s=lists[2::3]
uploader=s[0::2]

In [193]:
# making dataframe
df=pd.DataFrame({'Rank':rank,'Views':views,'Video Name':video_name,'Upload Date':upload_date,'Uploader':uploader})
df

,Rank,Views,Video Name,Upload Date,Uploader
0,1.,9.06,"""Baby Shark Dance""[22]","June 17, 2016",Pinkfong Kids' Songs & Stories
1,2.,7.47,"""Despacito""[24]","January 12, 2017",Luis Fonsi
2,3.,5.60,"""Johny Johny Yes Papa""[25]","October 8, 2016",LooLoo Kids
3,4.,5.40,"""Shape of You""[26]","January 30, 2017",Ed Sheeran
4,5.,5.20,"""See You Again""[27]","April 6, 2015",Wiz Khalifa
5,6.,4.45,"""Masha and the Bear – Recipe for Disaster""[30]","January 31, 2012",Get Movies
6,7.,4.39,"""Bath Song""[31]","May 2, 2018",Cocomelon – Nursery Rhymes
7,8.,4.35,"""Learning Colors – Colorful Eggs on a Farm""[32]","February 27, 2018",Miroshka TV
8,9.,4.25,"""Uptown Funk""[33]","November 19, 2014",Mark Ronson
9,10.,4.14,"""Gangnam Style""[34]","July 15, 2012",Psy
10,11.,4.04,"""Phonics Song with Two Words""[36]","March 6, 2014",ChuChu TV
11,12.,3.52,"""Sugar""[37]","January 14, 2015",Maroon 5
12,13.,3.49,"""Dame Tu Cosita""[38]","April 5, 2018",El Chombo
13,14.,3.45,"""Sorry""[39]","October 22, 2015",Justin Bieber
14,15.,3.40,"""Roar""[40]","September 5, 2013",Katy Perry
15,16.,3.35,"""Counting Stars""[41]","May 31, 2013",OneRepublic
16,17.,3.30,"""Thinking Out Loud""[42]","October 7, 2014",Ed Sheeran
17,18.,3.20,"""Wheels on the Bus""[43]","May 24, 2018",Cocomelon – Nursery Rhymes
18,19.,3.11,"""Dark Horse""[44]","February 20, 2014",Katy Perry
19,20.,3.11,"""Faded""[45]","December 3, 2015",Alan Walker
20,21.,3.08,"""Girls Like You""[46]","May 31, 2018",Maroon 5
21,22.,3.08,"""Shake It Off""[47]","August 18, 2014",Taylor Swift
22,23.,3.07,"""Lean On""[48]","March 22, 2015",Major Lazer
23,24.,3.07,"""Bailando""[49]","April 11, 2014",Enrique Iglesias
24,25.,3.04,"""Let Her Go""[50]","July 25, 2012",Passenger
25,26.,2.95,"""Mi Gente""[51]","June 29, 2017",J Balvin
26,27.,2.91,"""Perfect""[52]","November 9, 2017",Ed Sheeran
27,28.,2.91,"""Axel F""[53]","June 16, 2009",Crazy Frog
28,29.,2.90,"""Waka Waka (This Time for Africa)""[54]","June 4, 2010",Shakira
29,30.,2.86,"""Hello""[55]","October 22, 2015",Adele

# 2)Scrape the details team India’s international fixtures from bcci.tv.

In [23]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

#importing time
import time

In [24]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [25]:
# Opening the homepage
driver.get('https://www.bcci.tv/')

In [29]:
btn=driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(btn.get_attribute("href"))

In [141]:
# making empty lists
match_title=[]
series=[]
place=[]
date=[]
time=[]

# Extracting match_title from xpath
mt = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']")
for i in mt:
    match_title.append(i.text.replace('\n',''))
match_title_=[]
for i in match_title:
    match_title_.append(i[:3])
print(match_title_)

# Extracting match_title from match_title
place=[]
for i in match_title:
    place.append(i[4:])
print(place)

# Extracting series from xpath
s = driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
for i in s:
    series.append(i.text)
print(series)


# Extracting date and time from xpath
d = driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']")
for i in d:
    date.append(i.text.replace('\n',' '))

date_=[]
for i in date:
    date_.append(i[:-9])
print(date_)

# Extracting date and time from date_
time_=[]
for i in date:
    time_.append(i.split(None, 3))

for i in time_:
    time.append(i[3:])
print(time)

['1st', '2nd', '3rd', '4th', '5th']
['TestTrent Bridge, Nottingham', "TestLord's, London", 'TestHeadingley, Leeds', 'TestThe Oval, London', 'TestOld Trafford, Manchester']
['ENGLAND V INDIA 2021', 'ENGLAND V INDIA 2021', 'ENGLAND V INDIA 2021', 'ENGLAND V INDIA 2021', 'ENGLAND V INDIA 2021']
['Wednesday 04 AUGUST ', 'Thursday 12 AUGUST ', 'Wednesday 25 AUGUST ', 'Thursday 02 SEPTEMBER ', 'Friday 10 SEPTEMBER ']
[['15:30 IST'], ['15:30 IST'], ['15:30 IST'], ['15:30 IST'], ['15:30 IST']]

In [142]:
# making dataframe
df=pd.DataFrame({'Match Title':match_title_,'Series':series,'Place':place,'Date':date_,'Time':time__})
df

,Match Title,Series,Place,Date,Time
0,1st,ENGLAND V INDIA 2021,"TestTrent Bridge, Nottingham",Wednesday 04 AUGUST,[15:30 IST]
1,2nd,ENGLAND V INDIA 2021,"TestLord's, London",Thursday 12 AUGUST,[15:30 IST]
2,3rd,ENGLAND V INDIA 2021,"TestHeadingley, Leeds",Wednesday 25 AUGUST,[15:30 IST]
3,4th,ENGLAND V INDIA 2021,"TestThe Oval, London",Thursday 02 SEPTEMBER,[15:30 IST]
4,5th,ENGLAND V INDIA 2021,"TestOld Trafford, Manchester",Friday 10 SEPTEMBER,[15:30 IST]

# 3)Scrape the details of selenium exception from guru99.com.

In [11]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

#importing time
import time

In [12]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [13]:
# Opening the homepage
driver.get('https://www.guru99.com/')

In [15]:
search_button = driver.find_element_by_link_text("Selenium") # Locating search_button by link text
search_button.click()   # Clicking the button to start search

In [16]:
search_button = driver.find_element_by_xpath("//td [@class = 'responsivetable']/a [@title = 'Selenium Exception Handling (Common Exceptions List)']") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [20]:
# making empty nmae
name=[]

# Extracting name from xpath name
n=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
for i in n:
    name.append(i.text)
name=name[1:]
name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [21]:
# making empty des
des=[]

# Extracting name from xpath name
d=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
for i in d:
    des.append(i.text)
des=des[1:]
des

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 "Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn't found in the specified time.",
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 "It occurs when command can't be finished when the element is invalid.",
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 "This occurs when remote WebDriver does n't send valid commands as expected."]

In [22]:
# putting into dataframe
df=pd.DataFrame({'Name':name,'Description':des})
df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4)Scrape the details of State-wise GDP of India from statisticstime.com.

In [226]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

#importing time
import time

In [227]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [228]:
# Opening the homepage
driver.get('http://statisticstimes.com/')

In [229]:
search_button = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [230]:
search_button = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [233]:
search_button = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [234]:
#scraping rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    rank.append('No details available')
time.sleep(2)

In [235]:
rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [236]:
#scraping state
state=[]
try:
    s=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in s:
        state.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    state.append('No details available')
time.sleep(2)
state

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [237]:
#scraping GSDP at current price (19-20)
gsdp_19_20=[]
try:
    g=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in g:
        gsdp_19_20.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    gsdp_19_20.append('No details available')
time.sleep(2)
gsdp_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [238]:
#scraping GSDP at current price (18-19)
gsdp_18_19=[]
try:
    gs=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in gs:
        gsdp_18_19.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    gsdp_18_19.append('No details available')
time.sleep(2)
gsdp_18_19

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [239]:
#scraping Share(18-19)
share_18_19=[]
try:
    s=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in s:
        share_18_19.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    share_18_19.append('No details available')
time.sleep(2)
share_18_19

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [240]:
#scraping GDP($ billion)
gdp=[]
try:
    gd=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in gd:
        gdp.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    gdp.append('No details available')
time.sleep(2)
gdp

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [243]:
# making dataframe
df=pd.DataFrame({'Rank':rank,'State':state,'GSDP(19-20)':gsdp_19_20,'GSDP(18-19)':gsdp_18_19,'Share(18-19)':share_18_19,'GDP($billion)':gdp})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5) Scrape the details of trending repositories on Github.com.

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

#importing time
import time

In [2]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [3]:
# Opening the homepage
driver.get('https://github.com/')

In [4]:
search_button = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [5]:
search_button = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [6]:
# scraping titles
repository_title=[]
try:
    rt=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in rt:
        repository_title.append(i.text)
except NoSuchElementException:
    repository_title.append('No details available')

repository_title=repository_title[:21]
repository_title

['Azure / azure-sdk-for-net',
 'microsoft / vscode',
 'apache / pinot',
 'tannerlinsley / react-query',
 'datafuselabs / datafuse',
 'RPCS3 / rpcs3',
 '3b1b / manim',
 'badtuxx / DescomplicandoDocker',
 'badtuxx / DescomplicandoKubernetes',
 'kubernetes / kompose',
 '0voice / linux_kernel_wiki',
 'JetBrains / compose-jb',
 'alyssaxuu / mapus',
 'prometheus / prometheus',
 'mytechnotalent / Reverse-Engineering',
 'testjavascript / nodejs-integration-tests-best-practices',
 'metabase / metabase',
 'Blinue / Magpie',
 'dataease / dataease',
 'mrousavy / react-native-vision-camera',
 'geekxh / hello-algorithm']

In [7]:
#scraping descriptions
repository_description=[]
try:
    rd=driver.find_elements_by_xpath("//p[@class='col-9 color-text-secondary my-1 pr-4']")
    for i in rd:
        repository_description.append(i.text)
except NoSuchElementException:
    repository_description.append('No details available')
repository_description=repository_description[:21]
repository_description

['This repository is for active development of the Azure SDK for .NET. For consumers of the SDK we recommend visiting our public developer docs at https://docs.microsoft.com/en-us/dotnet/azure/ or our versioned developer docs at https://azure.github.io/azure-sdk-for-net.',
 'Visual Studio Code',
 'Apache Pinot (Incubating) - A realtime distributed OLAP datastore',
 '⚛️ Hooks for fetching, caching and updating asynchronous data in React',
 'A Modern Real-Time Data Processing & Analytics DBMS with Cloud-Native Architecture, built to make the Data Cloud easy',
 'PS3 emulator/debugger',
 'Animation engine for explanatory math videos',
 'Descomplicando o Docker, o livro.',
 'Go from Docker Compose to Kubernetes',
 'linux内核学习资料：200+经典内核文章，100+内核论文，50+内核项目，500+内核面试题，80+内核视频',
 'Jetpack Compose for Desktop and Web, a modern UI framework for Kotlin that makes building performant and beautiful user interfaces easy and enjoyable.',
 'A map tool with real-time collaboration 🗺️',
 'The Prometheus monitoring system and time series database.',
 'A FREE comprehensive reverse engineering course covering x86, x64, 32-bit ARM & 64-bit ARM architectures.',
 '✅ Master the art of the most powerful testing technique for Node.js: Component tests. Including super-comprehensive best practices list and an example app (August 2021)',
 'The simplest, fastest way to get business intelligence and analytics to everyone in your company 😋',
 '使游戏窗口全屏显示',
 '人人可用的开源数据可视化分析工具。',
 '📸 The Camera library that sees the vision.',
 '🌍 针对小白的算法训练 | 包括四部分：①.算法基础 ②.力扣图解 ③.大厂面经 ④.CS_汇总 | 附：1、千本开源电子书 2、百张技术思维导图（项目花了上百小时，希望可以点 star 支持，🌹感谢~）',
 'openpilot is an open source driver assistance system. openpilot performs the functions of Automated Lane Centering and Adaptive Cruise Control for over 100 supported car makes and models.']

In [8]:
# scraping counts
contributors_count=[]
try:
    cc=driver.find_elements_by_xpath("//a [@class = 'Link--muted d-inline-block mr-3']")
    for i in cc:
        contributors_count.append(i.text)
except NoSuchElementException:
    contributors_count.append('No details available')
contributors_count=contributors_count[:21]
contributors_count

['2,785',
 '2,858',
 '119,831',
 '19,617',
 '3,464',
 '730',
 '21,852',
 '1,052',
 '1,569',
 '138',
 '9,416',
 '1,481',
 '36,061',
 '4,185',
 '1,480',
 '214',
 '2,258',
 '816',
 '6,712',
 '554',
 '396']

In [9]:
# scraping language used
language_used=[]
try:
    lu=driver.find_elements_by_xpath("//span[@itemprop='programmingLanguage']")
    for i in lu:
        language_used.append(i.text)
except NoSuchElementException:
    language_used.append('No details available')
language_used=language_used[:21]
language_used

['C#',
 'TypeScript',
 'Java',
 'TypeScript',
 'Rust',
 'C++',
 'Python',
 'Shell',
 'Go',
 'Kotlin',
 'JavaScript',
 'Go',
 'C',
 'JavaScript',
 'Clojure',
 'HLSL',
 'Java',
 'Swift',
 'Java',
 'C++',
 'Java']

In [10]:
# putting into dataframe
df=pd.DataFrame({'Repository Title':repository_title,'repository Description':repository_description,'Contributors Count':contributors_count,'Language Used':language_used})
df

,Repository Title,repository Description,Contributors Count,Language Used
0,Azure / azure-sdk-for-net,This repository is for active development of t...,"2,785",C#
1,microsoft / vscode,Visual Studio Code,"2,858",TypeScript
2,apache / pinot,Apache Pinot (Incubating) - A realtime distrib...,"119,831",Java
3,tannerlinsley / react-query,"⚛️ Hooks for fetching, caching and updating as...","19,617",TypeScript
4,datafuselabs / datafuse,A Modern Real-Time Data Processing & Analytics...,"3,464",Rust
5,RPCS3 / rpcs3,PS3 emulator/debugger,730,C++
6,3b1b / manim,Animation engine for explanatory math videos,"21,852",Python
7,badtuxx / DescomplicandoDocker,"Descomplicando o Docker, o livro.","1,052",Shell
8,badtuxx / DescomplicandoKubernetes,Go from Docker Compose to Kubernetes,"1,569",Go
9,kubernetes / kompose,linux内核学习资料：200+经典内核文章，100+内核论文，50+内核项目，500+内核...,138,Kotlin
10,0voice / linux_kernel_wiki,"Jetpack Compose for Desktop and Web, a modern ...","9,416",JavaScript
11,JetBrains / compose-jb,A map tool with real-time collaboration 🗺️,"1,481",Go
12,alyssaxuu / mapus,The Prometheus monitoring system and time seri...,"36,061",C
13,prometheus / prometheus,A FREE comprehensive reverse engineering cours...,"4,185",JavaScript
14,mytechnotalent / Reverse-Engineering,✅ Master the art of the most powerful testing ...,"1,480",Clojure
15,testjavascript / nodejs-integration-tests-best...,"The simplest, fastest way to get business inte...",214,HLSL
16,metabase / metabase,使游戏窗口全屏显示,"2,258",Java
17,Blinue / Magpie,人人可用的开源数据可视化分析工具。,816,Swift
18,dataease / dataease,📸 The Camera library that sees the vision.,"6,712",Java
19,mrousavy / react-native-vision-camera,🌍 针对小白的算法训练 | 包括四部分：①.算法基础 ②.力扣图解 ③.大厂面经 ④.CS_...,554,C++
20,geekxh / hello-algorithm,openpilot is an open source driver assistance ...,396,Java

# 6) Scrape the details of top 100 songs on billboard.com.

In [270]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importng time
import time

In [271]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [272]:
# Opening the homepage
driver.get('https://www.billboard.com/')

In [286]:
search_button = driver.find_element_by_xpath("//nav[@class='header__subnav bg--light']/ul/li[2]") # Locating search_button by xpath
search_button.click()   # Clicking the button to start search

In [298]:
# scraping songs name
song_name=[]
try:
    sn=driver.find_elements_by_xpath("//ol[@class='chart-list__elements']/li/button/span/span[@class='chart-element__information__song text--truncate color--primary']")
    for i in sn:
        song_name.append(i.text)
except NoSuchElementException:
    song_name.append('No details available')
song_name

['Butter',
 'Industry Baby',
 'Good 4 U',
 'Stay',
 'Levitating',
 'Kiss Me More',
 'Bad Habits',
 'Montero (Call Me By Your Name)',
 'Permission To Dance',
 'Deja Vu',
 'Save Your Tears',
 'Peaches',
 'Leave The Door Open',
 'Fancy Like',
 "If I Didn't Love You",
 'Rapstar',
 'Blinding Lights',
 'Heartbreak Anniversary',
 'You Right',
 'Without You',
 'Astronaut In The Ocean',
 'Forever After All',
 'Every Chance I Get',
 'Leave Before You Love Me',
 'Lil Bit',
 'Single Saturday Night',
 'Beautiful Mistakes',
 'Thot Shit',
 'Late At Night',
 'Heat Waves',
 'Glad You Exist',
 "Drinkin' Beer. Talkin' God. Amen.",
 'Motley Crew',
 "Ain't Shit",
 'Telepatia',
 'Famous Friends',
 'Need To Know',
 "Beggin'",
 'Whole Lotta Money',
 'Best Friend',
 'Not Sober',
 "Don't Go Yet",
 'Mood',
 "My Ex's Best Friend",
 'Wild Side',
 'Wockesha',
 'Traitor',
 'Chasing After You',
 'Wants And Needs',
 'Yonaguni',
 'Todo de Ti',
 'Country Again',
 'Waves',
 'Things A Man Oughta Know',
 'Arcade',
 'One Too Many',
 'Over The Top',
 'You',
 'Essence',
 'Ball If I Want To',
 'Memory',
 "We Didn't Have Much",
 '2055',
 "Drunk (And I Don't Wanna Go Home)",
 'Blame It On You',
 'Settling Down',
 'Gone',
 'Way Less Sad',
 'my.life',
 'A-O-K',
 'Straightenin',
 'Tombstone',
 'Love Again',
 'AM',
 'Favorite Crime',
 'Come Through',
 'I Was On A Boat That Day',
 'Cold Beer Calling My Name',
 'You Should Probably Leave',
 'Happier',
 'Pepas',
 'My Boy',
 'Hats Off',
 'Red Light Green Light',
 'Fiel',
 'Next Girl',
 'NDA',
 'Better Believe',
 'Lick Back',
 "Memory I Don't Mess With",
 'Ski',
 '5500 Degrees',
 'Build A Bitch',
 'Twerkulator',
 'Brutal',
 'Minimum Wage',
 'Working',
 'Holy Smokes',
 'WUSYANAME',
 'Still Chose You']

In [299]:
# scraping artist name
artist_name=[]
try:
    an=driver.find_elements_by_xpath("//ol[@class='chart-list__elements']/li/button/span/span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in an:
        artist_name.append(i.text)
except NoSuchElementException:
    artist_name.append('No details available')
artist_name

['BTS',
 'Lil Nas X & Jack Harlow',
 'Olivia Rodrigo',
 'The Kid LAROI & Justin Bieber',
 'Dua Lipa Featuring DaBaby',
 'Doja Cat Featuring SZA',
 'Ed Sheeran',
 'Lil Nas X',
 'BTS',
 'Olivia Rodrigo',
 'The Weeknd & Ariana Grande',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Walker Hayes',
 'Jason Aldean & Carrie Underwood',
 'Polo G',
 'The Weeknd',
 'Giveon',
 'Doja Cat & The Weeknd',
 'The Kid LAROI',
 'Masked Wolf',
 'Luke Combs',
 'DJ Khaled Featuring Lil Baby & Lil Durk',
 'Marshmello X Jonas Brothers',
 'Nelly & Florida Georgia Line',
 'Cole Swindell',
 'Maroon 5 Featuring Megan Thee Stallion',
 'Megan Thee Stallion',
 'Roddy Ricch',
 'Glass Animals',
 'Dan + Shay',
 'Chase Rice Featuring Florida Georgia Line',
 'Post Malone',
 'Doja Cat',
 'Kali Uchis',
 'Chris Young + Kane Brown',
 'Doja Cat',
 'Maneskin',
 'BIA Featuring Nicki Minaj',
 'Saweetie Featuring Doja Cat',
 'The Kid LAROI Featuring Polo G & Stunna Gambino',
 'Camila Cabello',
 '24kGoldn Featuring iann dior',
 'Machine Gun Kelly X blackbear',
 'Normani Featuring Cardi B',
 'Moneybagg Yo',
 'Olivia Rodrigo',
 'Ryan Hurd With Maren Morris',
 'Drake Featuring Lil Baby',
 'Bad Bunny',
 'Rauw Alejandro',
 'Thomas Rhett',
 'Luke Bryan',
 'Lainey Wilson',
 'Duncan Laurence',
 'Keith Urban Duet With P!nk',
 'Smiley Featuring Drake',
 'Regard x Troye Sivan x Tate McRae',
 'Wizkid Featuring Tems',
 'DaBaby',
 'Kane Brown X blackbear',
 'Justin Moore',
 'Sleepy Hallow',
 'Elle King & Miranda Lambert',
 'Jason Aldean',
 'Miranda Lambert',
 'Dierks Bentley',
 'AJR',
 'J. Cole, 21 Savage & Morray',
 'Tai Verdes',
 'Migos',
 'Rod Wave',
 'Dua Lipa',
 'Nio Garcia X J Balvin X Bad Bunny',
 'Olivia Rodrigo',
 'H.E.R. Featuring Chris Brown',
 'Old Dominion',
 'Jameson Rodgers Featuring Luke Combs',
 'Chris Stapleton',
 'Olivia Rodrigo',
 'Farruko',
 'Elvie Shane',
 'Lil Baby, Lil Durk & Travis Scott',
 'DaBaby',
 'Los Legendarios, Wisin & Jhay Cortez',
 'Carly Pearce',
 'Billie Eilish',
 'Belly, The Weeknd & Young Thug',
 'EST Gee',
 'Lee Brice',
 'Young Thug & Gunna',
 'EST Gee Featuring Lil Baby, 42 Dugg & Rylo Rodriguez',
 'Bella Poarch',
 'City Girls',
 'Olivia Rodrigo',
 'Blake Shelton',
 'Tate McRae X Khalid',
 'Trippie Redd Featuring Lil Uzi Vert',
 'Tyler, The Creator Featuring YoungBoy Never Broke Again & Ty Dolla $ign',
 'The Kid LAROI Featuring Mustard']

In [303]:
# scraping last week rank
Last_week_rank=[]
try:
    lw=driver.find_elements_by_xpath("//ol[@class='chart-list__elements']/li/button/span/span/span[@class='chart-element__meta text--center color--secondary text--last']")
    for i in lw:
        Last_week_rank.append(i.text)
except NoSuchElementException:
    Last_week_rank.append('No details available')
Last_week_rank

['1 LW',
 '',
 '2 LW',
 '4 LW',
 '3 LW',
 '5 LW',
 '6 LW',
 '8 LW',
 '7 LW',
 '9 LW',
 '10 LW',
 '11 LW',
 '12 LW',
 '15 LW',
 '',
 '13 LW',
 '17 LW',
 '16 LW',
 '19 LW',
 '20 LW',
 '18 LW',
 '21 LW',
 '22 LW',
 '24 LW',
 '26 LW',
 '27 LW',
 '29 LW',
 '25 LW',
 '33 LW',
 '32 LW',
 '34 LW',
 '37 LW',
 '23 LW',
 '31 LW',
 '38 LW',
 '28 LW',
 '46 LW',
 '35 LW',
 '30 LW',
 '40 LW',
 '',
 '',
 '41 LW',
 '42 LW',
 '14 LW',
 '48 LW',
 '39 LW',
 '58 LW',
 '47 LW',
 '44 LW',
 '45 LW',
 '66 LW',
 '61 LW',
 '51 LW',
 '57 LW',
 '55 LW',
 '',
 '60 LW',
 '67 LW',
 '56 LW',
 '70 LW',
 '65 LW',
 '87 LW',
 '59 LW',
 '36 LW',
 '53 LW',
 '63 LW',
 '62 LW',
 '69 LW',
 '78 LW',
 '72 LW',
 '77 LW',
 '89 LW',
 '73 LW',
 '68 LW',
 '84 LW',
 '90 LW',
 '100 LW',
 '98 LW',
 '76 LW',
 '',
 '95 LW',
 '81 LW',
 '79 LW',
 '85 LW',
 '',
 '75 LW',
 '',
 '',
 '',
 '74 LW',
 '',
 '96 LW',
 '94 LW',
 '88 LW',
 '83 LW',
 '',
 '50 LW',
 '91 LW',
 '']

In [304]:
# scraping peak rank
peak_rank=[]
try:
    pr=driver.find_elements_by_xpath("//ol[@class='chart-list__elements']/li/button/span/span/span[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in pr:
        peak_rank.append(i.text)
except NoSuchElementException:
    peak_rank.append('No details available')
peak_rank

['1 Pk',
 '2 Pk',
 '1 Pk',
 '3 Pk',
 '2 Pk',
 '3 Pk',
 '5 Pk',
 '1 Pk',
 '1 Pk',
 '3 Pk',
 '1 Pk',
 '1 Pk',
 '1 Pk',
 '14 Pk',
 '15 Pk',
 '1 Pk',
 '1 Pk',
 '16 Pk',
 '11 Pk',
 '8 Pk',
 '6 Pk',
 '2 Pk',
 '20 Pk',
 '24 Pk',
 '23 Pk',
 '26 Pk',
 '13 Pk',
 '16 Pk',
 '20 Pk',
 '19 Pk',
 '31 Pk',
 '32 Pk',
 '13 Pk',
 '24 Pk',
 '25 Pk',
 '21 Pk',
 '37 Pk',
 '35 Pk',
 '16 Pk',
 '14 Pk',
 '41 Pk',
 '42 Pk',
 '1 Pk',
 '20 Pk',
 '14 Pk',
 '33 Pk',
 '9 Pk',
 '48 Pk',
 '2 Pk',
 '10 Pk',
 '32 Pk',
 '52 Pk',
 '53 Pk',
 '51 Pk',
 '55 Pk',
 '52 Pk',
 '57 Pk',
 '58 Pk',
 '59 Pk',
 '39 Pk',
 '50 Pk',
 '62 Pk',
 '63 Pk',
 '53 Pk',
 '30 Pk',
 '41 Pk',
 '26 Pk',
 '54 Pk',
 '2 Pk',
 '70 Pk',
 '23 Pk',
 '11 Pk',
 '73 Pk',
 '41 Pk',
 '16 Pk',
 '64 Pk',
 '77 Pk',
 '78 Pk',
 '79 Pk',
 '15 Pk',
 '81 Pk',
 '82 Pk',
 '16 Pk',
 '50 Pk',
 '62 Pk',
 '86 Pk',
 '39 Pk',
 '88 Pk',
 '89 Pk',
 '90 Pk',
 '18 Pk',
 '92 Pk',
 '56 Pk',
 '51 Pk',
 '12 Pk',
 '67 Pk',
 '88 Pk',
 '50 Pk',
 '14 Pk',
 '100 Pk']

In [305]:
# scraping weeks on board
weeks_on_board=[]
try:
    wb=driver.find_elements_by_xpath("//ol[@class='chart-list__elements']/li/button/span/span/span[@class='chart-element__meta text--center color--secondary text--week']")
    for i in wb:
        weeks_on_board.append(i.text)
except NoSuchElementException:
    weeks_on_board.append('No details available')
weeks_on_board

['10 WoC',
 '1 WoC',
 '11 WoC',
 '3 WoC',
 '43 WoC',
 '16 WoC',
 '5 WoC',
 '18 WoC',
 '3 WoC',
 '17 WoC',
 '33 WoC',
 '19 WoC',
 '21 WoC',
 '6 WoC',
 '1 WoC',
 '16 WoC',
 '86 WoC',
 '24 WoC',
 '5 WoC',
 '34 WoC',
 '24 WoC',
 '40 WoC',
 '13 WoC',
 '10 WoC',
 '19 WoC',
 '13 WoC',
 '21 WoC',
 '7 WoC',
 '8 WoC',
 '28 WoC',
 '25 WoC',
 '9 WoC',
 '3 WoC',
 '5 WoC',
 '23 WoC',
 '18 WoC',
 '7 WoC',
 '5 WoC',
 '3 WoC',
 '29 WoC',
 '1 WoC',
 '1 WoC',
 '51 WoC',
 '50 WoC',
 '2 WoC',
 '14 WoC',
 '10 WoC',
 '13 WoC',
 '21 WoC',
 '8 WoC',
 '9 WoC',
 '13 WoC',
 '6 WoC',
 '11 WoC',
 '16 WoC',
 '33 WoC',
 '1 WoC',
 '7 WoC',
 '4 WoC',
 '6 WoC',
 '3 WoC',
 '6 WoC',
 '2 WoC',
 '14 WoC',
 '14 WoC',
 '20 WoC',
 '20 WoC',
 '14 WoC',
 '11 WoC',
 '4 WoC',
 '11 WoC',
 '18 WoC',
 '2 WoC',
 '5 WoC',
 '10 WoC',
 '8 WoC',
 '4 WoC',
 '4 WoC',
 '4 WoC',
 '10 WoC',
 '1 WoC',
 '5 WoC',
 '8 WoC',
 '5 WoC',
 '7 WoC',
 '2 WoC',
 '3 WoC',
 '1 WoC',
 '1 WoC',
 '1 WoC',
 '15 WoC',
 '1 WoC',
 '11 WoC',
 '8 WoC',
 '10 WoC',
 '12 WoC',
 '5 WoC',
 '2 WoC',
 '5 WoC',
 '1 WoC']

In [306]:
# putting into dataframe
df=pd.DataFrame({'Song Name':song_name,'Artist Name':artist_name,'Last week Rank':Last_week_rank,'Peak Rank':peak_rank,'Weeks On Board':weeks_on_board})
df

,Song Name,Artist Name,Last week Rank,Peak Rank,Weeks On Board
0,Butter,BTS,1 LW,1 Pk,10 WoC
1,Industry Baby,Lil Nas X & Jack Harlow,,2 Pk,1 WoC
2,Good 4 U,Olivia Rodrigo,2 LW,1 Pk,11 WoC
3,Stay,The Kid LAROI & Justin Bieber,4 LW,3 Pk,3 WoC
4,Levitating,Dua Lipa Featuring DaBaby,3 LW,2 Pk,43 WoC
...,...,...,...,...,...
95,Minimum Wage,Blake Shelton,83 LW,67 Pk,12 WoC
96,Working,Tate McRae X Khalid,,88 Pk,5 WoC
97,Holy Smokes,Trippie Redd Featuring Lil Uzi Vert,50 LW,50 Pk,2 WoC
98,WUSYANAME,"Tyler, The Creator Featuring YoungBoy Never Br...",91 LW,14 Pk,5 WoC
99,Still Chose You,The Kid LAROI Featuring Mustard,,100 Pk,1 WoC

# 7) Scrape the details of Data science recruiters from naukri.com.

In [344]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importing time
import time

In [345]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [346]:
# Opening the homepage
driver.get('https://www.naukri.com/')
driver.maximize_window()

In [348]:
search_button = driver.find_element_by_xpath("//li/a[@title='Search Recruiters']") # Locating search_button by xpath
href=search_button.get_attribute('href')
driver.get(href)   # Clicking the button to start search

In [349]:
search_button = driver.find_element_by_xpath("//div[@class='inpWrap'] /input[@class='sugInp']") # Locating search_button by xpath
search_button.send_keys('Data Science')   # Clicking the button to start search

In [353]:
search_btn=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
search_btn.click()

In [407]:
# scraping name
name=[]
try:
    n=driver.find_elements_by_xpath("//p[@class='highlightable']/a/span[@class='fl ellipsis']")
    for i in n:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
name=name[:48]
name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury']

In [410]:
# scraping designation
desi=[]
try:
    d=driver.find_elements_by_xpath("//p[@class='highlightable']/span[@class='ellipsis clr']")
    for i in d:
        desi.append(i.text)
except NoSuchElementException:
    desi.append('No details available')
desi=desi[:48]
desi

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner']

In [411]:
# scraping company name
company=[]
try:
    c=driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
    for i in c:
        company.append(i.text)
except NoSuchElementException:
    company.append('No details available')
company=company[:48]
company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Infinitive Software Solutions Pvt.Ltd.',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai']

In [418]:
# scraping skills required
skills=[]
try:
    s=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
    for i in s:
        skills.append(i.text)
except NoSuchElementException:
    skills.append('No details available')
skills=skills[:48]
skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing']

In [415]:
# scraping location
location=[]
try:
    l=driver.find_elements_by_xpath("//small[@class='ellipsis']")
    for i in l:
        location.append(i.text)
except NoSuchElementException:
    if l=='Others':
        Location.append('-')
    elif l:
        Location.append(l.text)
location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Noida',
 'Mumbai']

In [419]:
# making dataframe
df=pd.DataFrame({'Name':name,'Designation':desi,'Company':company,'Skills':skills,'Location':location})
df

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
21,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
26,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
28,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
29,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Bengaluru / Bangalore
32,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Noida
33,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",New Delhi
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Noida
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Mumbai

# 8) Scrape the details of Highest selling novels.

In [420]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importing tinme
import time

In [421]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [422]:
# Opening the homepage
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
driver.maximize_window()

In [424]:
# scraping books name
book=[]
try:
    b=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in b:
        book.append(i.text)
except NoSuchElementException:
    book.append('No details available')
book

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [425]:
# scraping author name
author=[]
try:
    a=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in a:
        author.append(i.text)
except NoSuchElementException:
    author.append('No details available')
author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [426]:
# scraping volume sales
vs=[]
try:
    v=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in v:
        vs.append(i.text)
except NoSuchElementException:
    vs.append('No details available')
vs

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [427]:
# scraping publication
pub=[]
try:
    p=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in p:
        pub.append(i.text)
except NoSuchElementException:
    pub.append('No details available')
pub

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [428]:
# scraping genre
genre=[]
try:
    g=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in g:
        genre.append(i.text)
except NoSuchElementException:
    genre.append('No details available')
genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [429]:
# putting into dataframe
df=pd.DataFrame({'Book Name':book,'Author':author,'Volume Sales':vs,'Publisher':pub,'Genre':genre})
df

,Book Name,Author,Volume Sales,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9) Scrape the details most watched tv series of all time from imdb.com.

In [430]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importing time
import time

In [431]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [432]:
# Opening the homepage
driver.get('https://www.imdb.com/list/ls095964455/')
driver.maximize_window()

In [434]:
# scraping name
name=[]
try:
    n=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in n:
        name.append(i.text)
except NoSuchElementException:
    name.append('No details available')
name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [438]:
# scraping year
ys=[]
try:
    y=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in y:
        ys.append(i.text)
except NoSuchElementException:
    ys.append('No details available')
ys

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014– )',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999–2022)',
 '(2013– )',
 '(2004–2010)',
 '(2013– )',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016– )',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2022)',
 '(2013–2015)',
 '(2019– )',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015– )',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017– )',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017– )',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [439]:
# scraping genre
genre=[]
try:
    g=driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[5]")
    for i in g:
        genre.append(i.text)
except NoSuchElementException:
    genre.append('No details available')
genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Mystery',
 'Comedy, Romance',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Action, Drama, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Thriller',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama, Fantasy',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [440]:
# scraping run time
rt=[]
try:
    r=driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[3]")
    for i in r:
        rt.append(i.text)
except NoSuchElementException:
    rt.append('No details available')
rt

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [446]:
# scraping ratings
rating=[]
try:
    ra=driver.find_elements_by_xpath("//div[@class='ipl-rating-widget']/div/span[2]")
    for i in ra:
        rating.append(i.text)
except NoSuchElementException:
    rating.append('No details available')
rating

['9.2',
 '8.7',
 '8.2',
 '7.6',
 '7.6',
 '8',
 '6.8',
 '7.5',
 '7.6',
 '7.5',
 '8.3',
 '8.1',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.4',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.6',
 '8.6',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.4',
 '8.5',
 '8.2',
 '6.2',
 '7.4',
 '8.3',
 '7.8',
 '8.6',
 '7.9',
 '8.4',
 '9.2',
 '6.6',
 '8.1',
 '8.7',
 '8.8',
 '7.5',
 '8.3',
 '8.5',
 '7.7',
 '7.5',
 '7.7',
 '8.6',
 '6.9',
 '8.1',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.4',
 '6.8',
 '8.4',
 '7.5',
 '8.1',
 '7.8',
 '6.7',
 '8.7',
 '8.4',
 '6.6',
 '8',
 '8.9',
 '7.8',
 '7.5',
 '8.8',
 '8.1',
 '8.5',
 '8.3',
 '7.3',
 '8.7',
 '8.2',
 '6.5',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.3',
 '8.5',
 '6.5',
 '8.1',
 '8.6',
 '9.4',
 '7.8',
 '7.5',
 '7.8',
 '8',
 '7.1',
 '8.6']

In [453]:
# scraping votes
vote=[]
try:
    v=driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[2]")
    for i in v:
        vote.append(i.text)
except NoSuchElementException:
    vote.append('No details available')
vote=vote[1::2]
vote

['1,849,330',
 '886,613',
 '886,262',
 '266,567',
 '227,068',
 '284,673',
 '126,207',
 '266,439',
 '320,498',
 '414,856',
 '342,269',
 '743,563',
 '469,677',
 '839,487',
 '460,212',
 '155,940',
 '293,570',
 '286,723',
 '1,553,407',
 '264,551',
 '404,434',
 '492,621',
 '136,216',
 '133,036',
 '375,849',
 '212,693',
 '375,492',
 '375,210',
 '881,477',
 '624,310',
 '374,426',
 '345,926',
 '122,664',
 '115,447',
 '159,755',
 '144,087',
 '216,561',
 '444,790',
 '198,175',
 '378,319',
 '415,487',
 '56,220',
 '157,958',
 '476,831',
 '312,861',
 '59,819',
 '177,508',
 '213,231',
 '200,527',
 '205,217',
 '157,816',
 '665,774',
 '117,981',
 '312,794',
 '213,701',
 '512,493',
 '393,833',
 '426,277',
 '58,297',
 '104,555',
 '322,417',
 '68,393',
 '95,970',
 '196,043',
 '82,614',
 '71,049',
 '41,797',
 '140,010',
 '340,371',
 '248,860',
 '102,761',
 '175,664',
 '515,918',
 '94,954',
 '119,843',
 '348,198',
 '100,460',
 '194,926',
 '71,754',
 '16,691',
 '116,294',
 '127,539',
 '118,940',
 '32,884',
 '235,854',
 '114,983',
 '120,252',
 '68,870',
 '94,661',
 '168,411',
 '24,245',
 '170,295',
 '169,641',
 '596,645',
 '62,297',
 '45,072',
 '55,795',
 '171,943',
 '35,731',
 '195,253']

In [454]:
# putting into dataframe
df=pd.DataFrame({'Name':name,'Year Span':ys,'Genre':genre,'Run Time':rt,'Rating':rating,'Vote':vote})
df

,Name,Year Span,Genre,Run Time,Rating,Vote
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,849,330"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"886,613"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"886,262"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"266,567"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"227,068"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,072"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,795"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"171,943"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,731"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"195,253"

# 10) Details of Datasets from UCI machine learning repositories

In [30]:
# Importing Libraries
import numpy as np
import pandas as pd
import selenium

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# importing request
import requests

# importing beautifulsoup
from bs4 import BeautifulSoup as bs

# importing time
import time

In [31]:
# Activating webdriver
driver=webdriver.Edge('msedgedriver.exe')
time.sleep(3)

In [32]:
# Opening the homepage
driver.get('https://archive.ics.uci.edu/ml/index.php')
driver.maximize_window()

In [33]:
search_button = driver.find_element_by_xpath("//span[@class='normal']/b/a") # Locating search_button by xpath
search_button.click()

In [50]:
# scraping name
name=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[1]")]
name=name[1:]
name

['  Abalone',
 '  Adult',
 '  Annealing',
 '  Anonymous Microsoft Web Data',
 '  Arrhythmia',
 '  Artificial Characters',
 '  Audiology (Original)',
 '  Audiology (Standardized)',
 '  Auto MPG',
 '  Automobile',
 '  Badges',
 '  Balance Scale',
 '  Balloons',
 '  Breast Cancer',
 '  Breast Cancer Wisconsin (Original)',
 '  Breast Cancer Wisconsin (Prognostic)',
 '  Breast Cancer Wisconsin (Diagnostic)',
 '  Pittsburgh Bridges',
 '  Car Evaluation',
 '  Census Income',
 '  Chess (King-Rook vs. King-Knight)',
 '  Chess (King-Rook vs. King-Pawn)',
 '  Chess (King-Rook vs. King)',
 '  Chess (Domain Theories)',
 '  Bach Chorales',
 '  Connect-4',
 '  Credit Approval',
 '  Japanese Credit Screening',
 '  Computer Hardware',
 '  Contraceptive Method Choice',
 '  Covertype',
 '  Cylinder Bands',
 '  Dermatology',
 '  Diabetes',
 '  DGP2 - The Second Data Generation Program',
 '  Document Understanding',
 '  EBL Domain Theories',
 '  Echocardiogram',
 '  Ecoli',
 '  Flags',
 '  Function Finding',
 '  Glass Identification',
 "  Haberman's Survival",
 '  Hayes-Roth',
 '  Heart Disease',
 '  Hepatitis',
 '  Horse Colic',
 '  ICU',
 '  Image Segmentation',
 '  Internet Advertisements',
 '  Ionosphere',
 '  Iris',
 '  ISOLET',
 '  Kinship',
 '  Labor Relations',
 '  LED Display Domain',
 '  Lenses',
 '  Letter Recognition',
 '  Liver Disorders',
 '  Logic Theorist',
 '  Lung Cancer',
 '  Lymphography',
 '  Mechanical Analysis',
 '  Meta-data',
 '  Mobile Robots',
 '  Molecular Biology (Promoter Gene Sequences)',
 '  Molecular Biology (Protein Secondary Structure)',
 '  Molecular Biology (Splice-junction Gene Sequences)',
 "  MONK's Problems",
 '  Moral Reasoner',
 '  Multiple Features',
 '  Mushroom',
 '  Musk (Version 1)',
 '  Musk (Version 2)',
 '  Nursery',
 '  Othello Domain Theory',
 '  Page Blocks Classification',
 '  Optical Recognition of Handwritten Digits',
 '  Pen-Based Recognition of Handwritten Digits',
 '  Post-Operative Patient',
 '  Primary Tumor',
 '  Prodigy',
 '  Qualitative Structure Activity Relationships',
 '  Quadruped Mammals',
 '  Servo',
 '  Shuttle Landing Control',
 '  Solar Flare',
 '  Soybean (Large)',
 '  Soybean (Small)',
 '  Challenger USA Space Shuttle O-Ring',
 '  Low Resolution Spectrometer',
 '  Spambase',
 '  SPECT Heart',
 '  SPECTF Heart',
 '  Sponge',
 '  Statlog Project',
 '  Student Loan Relational',
 '  Teaching Assistant Evaluation',
 '  Tic-Tac-Toe Endgame',
 '  Thyroid Disease',
 '  Trains',
 '  University',
 '  Congressional Voting Records',
 '  Water Treatment Plant',
 '  Waveform Database Generator (Version 1)',
 '  Waveform Database Generator (Version 2)',
 '  Wine',
 '  Yeast',
 '  Zoo',
 '  Undocumented',
 '  Twenty Newsgroups',
 '  Australian Sign Language signs',
 '  Australian Sign Language signs (High Quality)',
 '  US Census Data (1990)',
 '  Census-Income (KDD)',
 '  Coil 1999 Competition Data',
 '  Corel Image Features',
 '  E. Coli Genes',
 '  EEG Database',
 '  El Nino',
 '  Entree Chicago Recommendation Data',
 '  CMU Face Images',
 '  Insurance Company Benchmark (COIL 2000)',
 '  Internet Usage Data',
 '  IPUMS Census Database',
 '  Japanese Vowels',
 '  KDD Cup 1998 Data',
 '  KDD Cup 1999 Data',
 '  M. Tuberculosis Genes',
 '  Movie',
 '  MSNBC.com Anonymous Web Data',
 '  NSF Research Award Abstracts 1990-2003',
 '  Pioneer-1 Mobile Robot Data',
 '  Pseudo Periodic Synthetic Time Series',
 '  Reuters-21578 Text Categorization Collection',
 '  Robot Execution Failures',
 '  Synthetic Control Chart Time Series',
 '  Syskill and Webert Web Page Ratings',
 '  UNIX User Data',
 '  Volcanoes on Venus - JARtool experiment',
 '  Statlog (Australian Credit Approval)',
 '  Statlog (German Credit Data)',
 '  Statlog (Heart)',
 '  Statlog (Landsat Satellite)',
 '  Statlog (Image Segmentation)',
 '  Statlog (Shuttle)',
 '  Statlog (Vehicle Silhouettes)',
 '  Connectionist Bench (Nettalk Corpus)',
 '  Connectionist Bench (Sonar, Mines vs. Rocks)',
 '  Connectionist Bench (Vowel Recognition - Deterding Data)',
 '  Economic Sanctions',
 '  Protein Data',
 '  Cloud',
 '  CalIt2 Building People Counts',
 '  Dodgers Loop Sensor',
 '  Poker Hand',
 '  MAGIC Gamma Telescope',
 '  UJI Pen Characters',
 '  Mammographic Mass',
 '  Forest Fires',
 '  Reuters Transcribed Subset',
 '  Bag of Words',
 '  Concrete Compressive Strength',
 '  Hill-Valley',
 '  Arcene',
 '  Dexter',
 '  Dorothea',
 '  Gisette',
 '  Madelon',
 '  Ozone Level Detection',
 '  Abscisic Acid Signaling Network',
 '  Parkinsons',
 '  Character Trajectories',
 '  Blood Transfusion Service Center',
 '  UJI Pen Characters (Version 2)',
 '  Semeion Handwritten Digit',
 '  SECOM',
 '  Plants',
 '  Libras Movement',
 '  Concrete Slump Test',
 '  Communities and Crime',
 '  Acute Inflammations',
 '  Wine Quality',
 '  URL Reputation',
 '  p53 Mutants',
 '  Parkinsons Telemonitoring',
 '  Demospongiae',
 '  Opinosis Opinion ⁄ Review',
 '  Breast Tissue',
 '  Cardiotocography',
 '  Wall-Following Robot Navigation Data',
 '  Spoken Arabic Digit',
 '  Localization Data for Person Activity',
 '  AutoUniv',
 '  Steel Plates Faults',
 '  MiniBooNE particle identification',
 '  YearPredictionMSD',
 '  PEMS-SF',
 '  OpinRank Review Dataset',
 '  Relative location of CT slices on axial axis',
 '  Online Handwritten Assamese Characters Dataset',
 '  PubChem Bioassay Data',
 '  Record Linkage Comparison Patterns',
 '  Communities and Crime Unnormalized',
 '  Vertebral Column',
 '  EMG Physical Action Data Set',
 '  Vicon Physical Action Data Set',
 '  Amazon Commerce reviews set',
 '  Amazon Access Samples',
 '  Reuter_50_50',
 '  Farm Ads',
 '  DBWorld e-mails',
 '  KEGG Metabolic Relation Network (Directed)',
 '  KEGG Metabolic Reaction Network (Undirected)',
 '  Bank Marketing',
 '  YouTube Comedy Slam Preference Data',
 '  Gas Sensor Array Drift Dataset',
 '  ILPD (Indian Liver Patient Dataset)',
 '  OPPORTUNITY Activity Recognition',
 '  Nomao',
 '  SMS Spam Collection',
 '  Skin Segmentation',
 '  Planning Relax',
 '  PAMAP2 Physical Activity Monitoring',
 '  Restaurant & consumer data',
 '  CNAE-9',
 '  Individual household electric power consumption',
 '  seeds',
 '  Northix',
 '  QtyT40I10D100K',
 '  Legal Case Reports',
 '  Human Activity Recognition Using Smartphones',
 '  One-hundred plant species leaves data set',
 '  Energy efficiency',
 '  Yacht Hydrodynamics',
 '  Fertility',
 '  Daphnet Freezing of Gait',
 '  3D Road Network (North Jutland, Denmark)',
 '  ISTANBUL STOCK EXCHANGE',
 '  Buzz in social media',
 '  First-order theorem proving',
 '  Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 '  Gas sensor arrays in open sampling settings',
 '  Climate Model Simulation Crashes',
 '  MicroMass',
 '  QSAR biodegradation',
 '  BLOGGER',
 '  Daily and Sports Activities',
 '  User Knowledge Modeling',
 '  Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 '  NYSK',
 '  Turkiye Student Evaluation',
 "  ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 '  EEG Eye State',
 '  Physicochemical Properties of Protein Tertiary Structure',
 '  seismic-bumps',
 '  banknote authentication',
 '  USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 '  YouTube Multiview Video Games Dataset',
 '  Gas Sensor Array Drift Dataset at Different Concentrations',
 '  Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 '  SkillCraft1 Master Table Dataset',
 '  Weight Lifting Exercises monitored with Inertial Measurement Units',
 '  SML2010',
 '  Bike Sharing Dataset',
 '  Predict keywords activities in a online social media',
 '  Thoracic Surgery Data',
 '  EMG dataset in Lower Limb',
 '  SUSY',
 '  HIGGS',
 '  Qualitative_Bankruptcy',
 '  LSVT Voice Rehabilitation',
 '  Dataset for ADL Recognition with Wrist-worn Accelerometer',
 '  Wilt',
 '  User Identification From Walking Activity',
 '  Activity Recognition from Single Chest-Mounted Accelerometer',
 '  Leaf',
 '  Dresses_Attribute_Sales',
 '  Tamilnadu Electricity Board Hourly Readings',
 '  Airfoil Self-Noise',
 '  Wholesale customers',
 '  Twitter Data set for Arabic Sentiment Analysis',
 '  Combined Cycle Power Plant',
 '  Urban Land Cover',
 '  Diabetes 130-US hospitals for years 1999-2008',
 '  Bach Choral Harmony',
 '  StoneFlakes',
 '  Tennis Major Tournament Match Statistics',
 '  Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 '  Gesture Phase Segmentation',
 '  Perfume Data',
 '  BlogFeedback',
 '  REALDISP Activity Recognition Dataset',
 '  Newspaper and magazine images segmentation dataset',
 '  AAAI 2014 Accepted Papers',
 '  Gas sensor array under flow modulation',
 '  Gas sensor array exposed to turbulent gas mixtures',
 '  UJIIndoorLoc',
 '  Sentence Classification',
 '  Dow Jones Index',
 '  sEMG for Basic Hand movements',
 '  AAAI 2013 Accepted Papers',
 '  Geographical Original of Music',
 '  Condition Based Maintenance of Naval Propulsion Plants',
 '  Grammatical Facial Expressions',
 '  NoisyOffice',
 '  MHEALTH Dataset',
 '  Student Performance',
 '  ElectricityLoadDiagrams20112014',
 '  Gas sensor array under dynamic gas mixtures',
 '  microblogPCU',
 '  Firm-Teacher_Clave-Direction_Classification',
 '  Dataset for Sensorless Drive Diagnosis',
 '  TV News Channel Commercial Detection Dataset',
 '  Phishing Websites',
 '  Greenhouse Gas Observing Network',
 '  Diabetic Retinopathy Debrecen Data Set',
 '  HIV-1 protease cleavage',
 '  Sentiment Labelled Sentences',
 '  Online News Popularity',
 '  Forest type mapping',
 '  wiki4HE',
 '  Online Video Characteristics and Transcoding Time Dataset',
 '  Chronic_Kidney_Disease',
 '  Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 '  Folio',
 '  Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 '  Cuff-Less Blood Pressure Estimation',
 '  Smartphone-Based Recognition of Human Activities and Postural Transitions',
 '  Mice Protein Expression',
 '  UJIIndoorLoc-Mag',
 '  Heterogeneity Activity Recognition',
 '  Educational Process Mining (EPM): A Learning Analytics Data Set',
 '  HEPMASS',
 '  Indoor User Movement Prediction from RSS data',
 '  Open University Learning Analytics dataset',
 '  default of credit card clients',
 '  Mesothelioma’s disease data set',
 '  Online Retail',
 '  SIFT10M',
 '  GPS Trajectories',
 '  Detect Malacious Executable(AntiVirus)',
 '  Occupancy Detection',
 '  Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 '  News Aggregator',
 '  Air Quality',
 '  Twin gas sensor arrays',
 '  Gas sensors for home activity monitoring',
 '  Facebook Comment Volume Dataset',
 '  Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 '  Polish companies bankruptcy data',
 '  Activity Recognition system based on Multisensor data fusion (AReM)',
 '  Dota2 Games Results',
 '  Facebook metrics',
 '  UbiqLog (smartphone lifelogging)',
 '  NIPS Conference Papers 1987-2015',
 '  HTRU2',
 '  Drug consumption (quantified)',
 '  Appliances energy prediction',
 '  Miskolc IIS Hybrid IPS',
 '  KDC-4007 dataset Collection',
 '  Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 '  DrivFace',
 '  Website Phishing',
 '  YouTube Spam Collection',
 '  Beijing PM2.5 Data',
 '  Cargo 2000 Freight Tracking and Tracing',
 '  Cervical cancer (Risk Factors)',
 '  Quality Assessment of Digital Colposcopies',
 '  KASANDR',
 '  FMA: A Dataset For Music Analysis',
 '  Air quality',
 '  Epileptic Seizure Recognition',
 '  Devanagari Handwritten Character Dataset',
 '  Stock portfolio performance',
 '  MoCap Hand Postures',
 '  Early biomarkers of Parkinson�s disease based on natural connected speech',
 '  Data for Software Engineering Teamwork Assessment in Education Setting',
 '  PM2.5 Data of Five Chinese Cities',
 '  Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 '  Sales_Transactions_Dataset_Weekly',
 '  Las Vegas Strip',
 '  Eco-hotel',
 '  MEU-Mobile KSD',
 '  Crowdsourced Mapping',
 '  gene expression cancer RNA-Seq',
 '  Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 '  chestnut – LARVIC',
 '  Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 '  Motion Capture Hand Postures',
 '  Anuran Calls (MFCCs)',
 '  TTC-3600: Benchmark dataset for Turkish text categorization',
 '  Gastrointestinal Lesions in Regular Colonoscopy',
 '  Daily Demand Forecasting Orders',
 '  Paper Reviews',
 '  extention of Z-Alizadeh sani dataset',
 '  Z-Alizadeh Sani',
 '  Dynamic Features of VirusShare Executables',
 '  IDA2016Challenge',
 '  DSRC Vehicle Communications',
 '  Mturk User-Perceived Clusters over Images',
 '  Character Font Images',
 '  DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 '  Autistic Spectrum Disorder Screening Data for Children',
 '  Autistic Spectrum Disorder Screening Data for Adolescent',
 '  APS Failure at Scania Trucks',
 '  Wireless Indoor Localization',
 '  HCC Survival',
 '  CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 '  University of Tehran Question Dataset 2016 (UTQD.2016)',
 '  Autism Screening Adult',
 '  Activity recognition with healthy older people using a batteryless wearable sensor',
 '  Immunotherapy Dataset',
 '  Cryotherapy Dataset',
 '  OCT data & Color Fundus Images of Left & Right Eyes',
 '  Discrete Tone Image Dataset',
 '  News Popularity in Multiple Social Media Platforms',
 '  Ultrasonic flowmeter diagnostics',
 '  ICMLA 2014 Accepted Papers Data Set',
 '  BLE RSSI Dataset for Indoor localization and Navigation',
 '  Container Crane Controller Data Set',
 '  Residential Building Data Set',
 '  Health News in Twitter',
 '  chipseq',
 '  SGEMM GPU kernel performance',
 '  Repeat Consumption Matrices',
 '  detection_of_IoT_botnet_attacks_N_BaIoT',
 '  Absenteeism at work',
 '  SCADI',
 '  Condition monitoring of hydraulic systems',
 '  Carbon Nanotubes',
 '  Optical Interconnection Network',
 '  Sports articles for objectivity analysis',
 '  Breast Cancer Coimbra',
 '  GNFUV Unmanned Surface Vehicles Sensor Data',
 '  Dishonest Internet users Dataset',
 '  Victorian Era Authorship Attribution',
 '  Simulated Falls and Daily Living Activities Data Set',
 '  Multimodal Damage Identification for Humanitarian Computing',
 '  EEG Steady-State Visual Evoked Potential Signals',
 '  Roman Urdu Data Set',
 '  Avila',
 '  PANDOR',
 '  Drug Review Dataset (Druglib.com)',
 '  Drug Review Dataset (Drugs.com)',
 '  Physical Unclonable Functions',
 '  Superconductivty Data',
 '  WESAD (Wearable Stress and Affect Detection)',
 '  GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 '  Student Academics Performance',
 '  Online Shoppers Purchasing Intention Dataset',
 '  PMU-UD',
 "  Parkinson's Disease Classification",
 '  Electrical Grid Stability Simulated Data',
 '  Caesarian Section Classification Dataset',
 '  BAUM-1',
 '  BAUM-2',
 '  Audit Data',
 '  BuddyMove Data Set',
 '  Real estate valuation data set',
 '  Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 '  Somerville Happiness Survey',
 '  2.4 GHZ Indoor Channel Measurements',
 '  EMG data for gestures',
 '  Parking Birmingham',
 '  Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 '  Travel Reviews',
 '  Tarvel Review Ratings',
 '  Rice Leaf Diseases',
 '  Gas sensor array temperature modulation',
 '  Facebook Live Sellers in Thailand',
 '  Parkinson Dataset with replicated acoustic features',
 '  Metro Interstate Traffic Volume',
 '  Query Analytics Workloads Dataset',
 '  Wave Energy Converters',
 '  PPG-DaLiA',
 '  Alcohol QCM Sensor Dataset',
 '  Divorce Predictors data set',
 '  Incident management process enriched event log',
 '  Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 '  MEx',
 '  Beijing Multi-Site Air-Quality Data',
 '  Online Retail II',
 '  Hepatitis C Virus (HCV) for Egyptian patients',
 '  QSAR fish toxicity',
 '  QSAR aquatic toxicity',
 '  Human Activity Recognition from Continuous Ambient Sensor Data',
 '  WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 '  QSAR oral toxicity',
 '  QSAR androgen receptor',
 '  QSAR Bioconcentration classes dataset',
 '  QSAR fish bioconcentration factor (BCF)',
 '  A study of Asian Religious and Biblical Texts',
 '  Real-time Election Results: Portugal 2019',
 '  Bias correction of numerical prediction model temperature forecast',
 '  Bar Crawl: Detecting Heavy Drinking',
 '  Kitsune Network Attack Dataset',
 '  Shoulder Implant X-Ray Manufacturer Classification',
 '  Speaker Accent Recognition',
 '  Heart failure clinical records',
 '  Deepfakes: Medical Image Tamper Detection',
 '  selfBACK',
 '  South German Credit',
 '  Exasens',
 '  Swarm Behaviour',
 '  Crop mapping using fused optical-radar data set',
 '  BitcoinHeistRansomwareAddressDataset',
 '  Facebook Large Page-Page Network',
 '  Amphibians',
 '  Early stage diabetes risk prediction dataset.',
 '  Turkish Spam V01',
 '  Stock keeping units',
 '  Demand Forecasting for a store',
 '  Detect Malware Types',
 '  Wave Energy Converters',
 '  Youtube cookery channels viewers comments in Hinglish',
 '  Pedestrian in Traffic Dataset',
 '  Cervical Cancer Behavior Risk',
 '  Sattriya_Dance_Single_Hand_Gestures Dataset',
 '  Divorce Predictors data set',
 '  3W dataset',
 '  Malware static and dynamic features VxHeaven and Virus Total',
 '  Internet Firewall Data',
 '  User Profiling and Abusive Language Detection Dataset',
 '  Estimation of obesity levels based on eating habits and physical condition',
 '  Rice (Cammeo and Osmancik)',
 '  Vehicle routing and scheduling problems',
 '  Algerian Forest Fires Dataset',
 '  Breath Metabolomics',
 '  Horton General Hospital',
 '  UrbanGB, urban road accidents coordinates labelled by the urban center',
 '  Gas Turbine CO and NOx Emission Data Set',
 '  Activity recognition using wearable physiological measurements',
 '  clickstream data for online shopping',
 '  CNNpred: CNN-based stock market prediction using a diverse set of variables',
 '  Apartment for rent classified',
 '  : Simulated Data set of Iraqi tourism places',
 '  Nasarian CAD Dataset',
 '  Monolithic Columns in Troad and Mysia Region',
 '  Bar Crawl: Detecting Heavy Drinking',
 '  Seoul Bike Sharing Demand',
 '  Person Classification Gait Data',
 '  Shill Bidding Dataset',
 '  Iranian Churn Dataset',
 '  Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 '  Bone marrow transplant: children',
 '  Exasens',
 '  COVID-19 Surveillance',
 '  Refractive errors',
 '  Shoulder Implant X-Ray Manufacturer Classification',
 '  CLINC150',
 '  HCV data',
 '  Taiwanese Bankruptcy Prediction',
 '  South German Credit (UPDATE)',
 '  IIWA14-R820-Gazebo-Dataset-10Trajectories',
 '  Guitar Chords finger positions',
 '  Russian Corpus of Biographical Texts',
 '  Codon usage',
 '  Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 '  Myocardial infarction complications',
 '  Hungarian Chickenpox Cases',
 '  Simulated data for survival modelling',
 '  Student Performance on an entrance examination',
 '  Chemical Composition of Ceramic Samples',
 '  Labeled Text Forum Threads Dataset',
 '  Stock keeping units',
 '  BLE RSSI dataset for Indoor localization',
 '  Basketball dataset',
 '  GitHub MUSAE',
 '  Anticancer peptides',
 '  Monolithic Columns in Troad and Mysia Region',
 '  Gender by Name',
 '  Iranian Churn Dataset',
 '  Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 '  Shoulder Implant Manufacture Classification',
 '  LastFM Asia Social Network',
 '  Wheat kernels',
 '  Productivity Prediction of Garment Employees',
 '  Multi-view Brain Networks',
 '  LastFM Asia Social Network',
 '  Wisesight Sentiment Corpus',
 '  AI4I 2020 Predictive Maintenance Dataset',

In [51]:
# scraping data_type
data_type=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[2]")]
data_type=data_type[1:]
data_type

['Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 ' ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 ' ',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ']

In [52]:
# scraping default_task
default_task=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[3]")]
default_task=default_task[1:]
default_task

['Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Function-Learning ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Relational-Learning ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Recommender-Systems ',
 'Classification ',
 'Regression, Description ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Regression, Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering, Causa ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 ' ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Clustering ',
 'Classification, Regression ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Clustering ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Recommendation ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Regression, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Regression ']

In [53]:
# scraping attribute_type
attribute_type=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[4]")]
attribute_type=attribute_type[1:]
attribute_type

['Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 ' ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Real, Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer, Real ',
 ' ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Real ',
 ' ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical ',
 ' ',
 'Categorical, Real ',
 ' ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Categorical ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Categorical ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Integer ',
 'Integer ',
 'Integer ',
 ' ',
 'Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ']

In [54]:
# scraping instance
instance=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[5]")]
instance=instance[1:]
instance

['4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ',
 '294 ',
 '625 ',
 '16 ',
 '286 ',
 '699 ',
 '198 ',
 '569 ',
 '108 ',
 '1728 ',
 '48842 ',
 ' ',
 '3196 ',
 '28056 ',
 ' ',
 '100 ',
 '67557 ',
 '690 ',
 '125 ',
 '209 ',
 '1473 ',
 '581012 ',
 '512 ',
 '366 ',
 ' ',
 ' ',
 ' ',
 ' ',
 '132 ',
 '336 ',
 '194 ',
 '352 ',
 '214 ',
 '306 ',
 '160 ',
 '303 ',
 '155 ',
 '368 ',
 ' ',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '57 ',
 ' ',
 '24 ',
 '20000 ',
 '345 ',
 ' ',
 '32 ',
 '148 ',
 '209 ',
 '528 ',
 ' ',
 '106 ',
 '128 ',
 '3190 ',
 '432 ',
 '202 ',
 '2000 ',
 '8124 ',
 '476 ',
 '6598 ',
 '12960 ',
 ' ',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 ' ',
 ' ',
 ' ',
 '167 ',
 '15 ',
 '1389 ',
 '307 ',
 '47 ',
 '23 ',
 '531 ',
 '4601 ',
 '267 ',
 '267 ',
 '76 ',
 ' ',
 '1000 ',
 '151 ',
 '958 ',
 '7200 ',
 '10 ',
 '285 ',
 '435 ',
 '527 ',
 '5000 ',
 '5000 ',
 '178 ',
 '1484 ',
 '101 ',
 ' ',
 '20000 ',
 '6650 ',
 '2565 ',
 '2458285 ',
 '299285 ',
 '340 ',
 '68040 ',
 ' ',
 '122 ',
 '178080 ',
 '50672 ',
 '640 ',
 '9000 ',
 '10104 ',
 '256932 ',
 '640 ',
 '191779 ',
 '4000000 ',
 ' ',
 '10000 ',
 '989818 ',
 '129000 ',
 ' ',
 '100000 ',
 '21578 ',
 '463 ',
 '600 ',
 '332 ',
 ' ',
 ' ',
 '690 ',
 '1000 ',
 '270 ',
 '6435 ',
 '2310 ',
 '58000 ',
 '946 ',
 '20008 ',
 '208 ',
 '528 ',
 ' ',
 ' ',
 '1024 ',
 '10080 ',
 '50400 ',
 '1025010 ',
 '19020 ',
 '1364 ',
 '961 ',
 '517 ',
 '200 ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '1593 ',
 '1567 ',
 '22632 ',
 '360 ',
 '103 ',
 '1994 ',
 '120 ',
 '4898 ',
 '2396130 ',
 '16772 ',
 '5875 ',
 '503 ',
 '51 ',
 '106 ',
 '2126 ',
 '5456 ',
 '8800 ',
 '164860 ',
 ' ',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 ' ',
 '53500 ',
 '8235 ',
 ' ',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '30000 ',
 '2500 ',
 '4143 ',
 '64 ',
 '53414 ',
 '65554 ',
 '45211 ',
 '1138562 ',
 '13910 ',
 '583 ',
 '2551 ',
 '34465 ',
 '5574 ',
 '245057 ',
 '182 ',
 '3850505 ',
 '138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '3960456 ',
 ' ',
 '10299 ',
 '1600 ',
 '768 ',
 '308 ',
 '100 ',
 '237 ',
 '434874 ',
 '536 ',
 '140000 ',
 '6118 ',
 '165632 ',
 '18000 ',
 '540 ',
 '931 ',
 '1055 ',
 '100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '10421 ',
 '5820 ',
 '403 ',
 '14980 ',
 '45730 ',
 '2584 ',
 '1372 ',
 '306 ',
 '120000 ',
 '13910 ',
 '2747 ',
 '3395 ',
 '39242 ',
 '4137 ',
 '17389 ',
 '51 ',
 '470 ',
 '132 ',
 '5000000 ',
 '11000000 ',
 '250 ',
 '126 ',
 ' ',
 '4889 ',
 ' ',
 ' ',
 '340 ',
 '501 ',
 '45781 ',
 '1503 ',
 '440 ',
 '2000 ',
 '9568 ',
 '168 ',
 '100000 ',
 '5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '101 ',
 '399 ',
 '58 ',
 '180 ',
 '21048 ',
 ' ',
 '750 ',
 '3000 ',
 '150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '10800 ',
 '58509 ',
 '129685 ',
 '2456 ',
 '2921 ',
 '1151 ',
 '6590 ',
 '3000 ',
 '39797 ',
 '326 ',
 '913 ',
 '168286 ',
 '400 ',
 '314080 ',
 '637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 ' ',
 '30000 ',
 '324 ',
 '541909 ',
 '11164866 ',
 '163 ',
 '373 ',
 '20560 ',
 '40 ',
 '422937 ',
 '9358 ',
 '640 ',
 '919438 ',
 '40949 ',
 '5744 ',
 '10503 ',
 '42240 ',
 '102944 ',
 '500 ',
 '9782222 ',
 '11463 ',
 '17898 ',
 '1885 ',
 '19735 ',
 '1540 ',
 '4007 ',
 '153540 ',
 '606 ',
 '1353 ',
 '1956 ',
 '43824 ',
 '3942 ',
 '858 ',
 '287 ',
 '17764280 ',
 '106574 ',
 '9358 ',
 '11500 ',
 '92000 ',
 '315 ',
 '78095 ',
 '130 ',
 '74 ',
 '52854 ',
 '77 ',
 '811 ',
 '504 ',
 '401 ',
 '2856 ',
 '10546 ',
 '801 ',
 '1540 ',
 '1451 ',
 '1075 ',
 '78095 ',
 '7195 ',
 '3600 ',
 '76 ',
 '60 ',
 '405 ',
 '303 ',
 '303 ',
 '107888 ',
 '76000 ',
 '10000 ',
 '180 ',
 '745000 ',
 '12234 ',
 '292 ',
 '104 ',
 '60000 ',
 '2000 ',
 '165 ',
 '217 ',
 '1175 ',
 '704 ',
 '75128 ',
 '90 ',
 '90 ',
 '50 ',
 '71 ',
 '93239 ',
 '540 ',
 '105 ',
 '6611 ',
 '15 ',
 '372 ',
 '58000 ',
 '4960 ',
 '241600 ',
 '130000 ',
 '7062606 ',
 '740 ',
 '70 ',
 '2205 ',
 '10721 ',
 '640 ',
 '1000 ',
 '116 ',
 '1672 ',
 '322 ',
 '93600 ',
 '3060 ',
 '5879 ',
 '9200 ',
 '20000 ',
 '20867 ',
 ' ',
 '4143 ',
 '215063 ',
 '6000000 ',
 '21263 ',
 '63000000 ',
 '10190 ',
 '300 ',
 '12330 ',
 '5180 ',
 '756 ',
 '10000 ',
 '80 ',
 '1184 ',
 '1047 ',
 '777 ',
 '249 ',
 '414 ',
 ' ',
 '143 ',
 '7840 ',
 '30000 ',
 '35717 ',
 '135 ',
 '980 ',
 '5456 ',
 '120 ',
 '4095000 ',
 '7051 ',
 '240 ',
 '48204 ',
 '260000 ',
 '288000 ',
 '8300000 ',
 '125 ',
 '170 ',
 '141712 ',
 '3916 ',
 '6262 ',
 '420768 ',
 '1067371 ',
 '1385 ',
 '908 ',
 '546 ',
 '13956534 ',
 '15630426 ',
 '8992 ',
 '1687 ',
 '779 ',
 '1056 ',
 '590 ',
 '21643 ',
 '7750 ',
 '14057567 ',
 '27170754 ',
 '597 ',
 '329 ',
 '299 ',
 '20000 ',
 '26136 ',
 '1000 ',
 '399 ',
 '24017 ',
 '325834 ',
 '2916697 ',
 '22470 ',
 '189 ',
 '520 ',
 '826 ',
 '2279 ',
 '28764 ',
 '7107 ',
 '288000 ',
 '9800 ',
 '4760 ',
 '72 ',
 '1450 ',
 '170 ',
 '1984 ',
 '2955 ',
 '65532 ',
 '65919 ',
 '2111 ',
 '3810 ',
 '18 ',
 '244 ',
 '104 ',
 '139 ',
 '360177 ',
 '36733 ',
 '4480 ',
 '165474 ',
 '1985 ',
 '10000 ',
 '232 ',
 '150 ',
 '11 ',
 '14057567 ',
 '8760 ',
 '48 ',
 '6321 ',
 '3150 ',
 '17256 ',
 '187 ',
 '399 ',
 '14 ',
 '467 ',
 '597 ',
 '23700 ',
 '615 ',
 '6819 ',
 '1000 ',
 ' ',
 '2633 ',
 '200 ',
 '13028 ',
 '800 ',
 '1700 ',
 '521 ',
 '120000 ',
 '666 ',
 '88 ',
 '200 ',
 '2279 ',
 '23570 ',
 '10000 ',
 '37700 ',
 '1850 ',
 '11 ',
 '147270 ',
 '3150 ',
 '17256 ',
 '597 ',
 '7624 ',
 '314 ',
 '1197 ',
 '70 ',
 '7624 ',
 '26737 ',
 '10000 ',
 '13611 ',
 '12684 ',
 '48 ',
 '731 ',
 '731 ',
 '557 ']

In [55]:
# scraping attributes
attributes=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[6]")]
attributes=attributes[1:]
attributes

['8 ',
 '14 ',
 '38 ',
 '294 ',
 '279 ',
 '7 ',
 ' ',
 '69 ',
 '8 ',
 '26 ',
 '1 ',
 '4 ',
 '4 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '22 ',
 '36 ',
 '6 ',
 ' ',
 '6 ',
 '42 ',
 '15 ',
 ' ',
 '9 ',
 '9 ',
 '54 ',
 '39 ',
 '33 ',
 '20 ',
 ' ',
 ' ',
 ' ',
 '12 ',
 '8 ',
 '30 ',
 ' ',
 '10 ',
 '3 ',
 '5 ',
 '75 ',
 '19 ',
 '27 ',
 ' ',
 '19 ',
 '1558 ',
 '34 ',
 '4 ',
 '617 ',
 '12 ',
 '16 ',
 '7 ',
 '4 ',
 '16 ',
 '7 ',
 ' ',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 ' ',
 '58 ',
 ' ',
 '61 ',
 '7 ',
 ' ',
 '649 ',
 '22 ',
 '168 ',
 '168 ',
 '8 ',
 ' ',
 '10 ',
 '64 ',
 '16 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '72 ',
 '4 ',
 '6 ',
 '10 ',
 '35 ',
 '35 ',
 '4 ',
 '102 ',
 '57 ',
 '22 ',
 '44 ',
 '45 ',
 ' ',
 ' ',
 '5 ',
 '9 ',
 '21 ',
 '32 ',
 '17 ',
 '16 ',
 '38 ',
 '21 ',
 '40 ',
 '13 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '15 ',
 '22 ',
 '68 ',
 '40 ',
 '17 ',
 '89 ',
 ' ',
 '4 ',
 '12 ',
 ' ',
 ' ',
 '86 ',
 '72 ',
 '61 ',
 '12 ',
 '481 ',
 '42 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '5 ',
 '90 ',
 ' ',
 '5 ',
 ' ',
 ' ',
 '14 ',
 '20 ',
 '13 ',
 '36 ',
 '19 ',
 '9 ',
 '18 ',
 '4 ',
 '60 ',
 '10 ',
 ' ',
 ' ',
 '10 ',
 '4 ',
 '3 ',
 '11 ',
 '11 ',
 ' ',
 '6 ',
 '13 ',
 ' ',
 '100000 ',
 '9 ',
 '101 ',
 '10000 ',
 '20000 ',
 '100000 ',
 '5000 ',
 '500 ',
 '73 ',
 '43 ',
 '23 ',
 '3 ',
 '5 ',
 ' ',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 ' ',
 ' ',
 '10 ',
 '23 ',
 '24 ',
 '13 ',
 '8 ',
 ' ',
 '27 ',
 '50 ',
 '90 ',
 '138672 ',
 ' ',
 '386 ',
 ' ',
 ' ',
 '12 ',
 '147 ',
 '6 ',
 '8 ',
 '27 ',
 '10000 ',
 '20000 ',
 '10000 ',
 '54877 ',
 '4702 ',
 '24 ',
 '29 ',
 '17 ',
 '3 ',
 '128 ',
 '10 ',
 '242 ',
 '120 ',
 ' ',
 '4 ',
 '13 ',
 '52 ',
 '47 ',
 '857 ',
 '9 ',
 '7 ',
 '200 ',
 '4 ',
 ' ',
 '561 ',
 '64 ',
 '8 ',
 '7 ',
 '10 ',
 '9 ',
 '4 ',
 '8 ',
 '77 ',
 '51 ',
 '18 ',
 '1950000 ',
 '18 ',
 '1300 ',
 '41 ',
 '6 ',
 '5625 ',
 '5 ',
 ' ',
 '7 ',
 '33 ',
 '5 ',
 '15 ',
 '9 ',
 '19 ',
 '5 ',
 '5 ',
 '1000000 ',
 '129 ',
 ' ',
 '20 ',
 '152 ',
 '24 ',
 '16 ',
 '35 ',
 '17 ',
 '5 ',
 '18 ',
 '28 ',
 '7 ',
 '309 ',
 '3 ',
 '6 ',
 ' ',
 ' ',
 '16 ',
 '13 ',
 '5 ',
 '6 ',
 '8 ',
 '2 ',
 '4 ',
 '148 ',
 '55 ',
 '17 ',
 '8 ',
 '42 ',
 '26 ',
 '50 ',
 '2 ',
 '281 ',
 '120 ',
 ' ',
 '6 ',
 '120432 ',
 '150000 ',
 '529 ',
 ' ',
 '16 ',
 '2500 ',
 '5 ',
 '68 ',
 '16 ',
 '100 ',
 '216 ',
 '23 ',
 '33 ',
 '140256 ',
 '19 ',
 '20 ',
 '20 ',
 '49 ',
 '12 ',
 '30 ',
 '5232 ',
 '20 ',
 '1 ',
 ' ',
 '61 ',
 '27 ',
 '53 ',
 '11 ',
 '25 ',
 '0 ',
 '20 ',
 '9 ',
 '3 ',
 '561 ',
 '82 ',
 '13 ',
 '16 ',
 '13 ',
 '28 ',
 '4 ',
 ' ',
 '24 ',
 '34 ',
 '8 ',
 '128 ',
 '15 ',
 '513 ',
 '7 ',
 '7 ',
 '5 ',
 '15 ',
 '480000 ',
 '11 ',
 '54 ',
 '561 ',
 '64 ',
 '6 ',
 '116 ',
 '19 ',
 ' ',
 '5812 ',
 '9 ',
 '32 ',
 '29 ',
 '67 ',
 ' ',
 '25 ',
 '6400 ',
 '10 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 ' ',
 '12 ',
 '38 ',
 '65 ',
 '102 ',
 '86 ',
 '7 ',
 '53 ',
 '20 ',
 '1 ',
 '71 ',
 '29 ',
 '20531 ',
 '65 ',
 '3 ',
 '22 ',
 '38 ',
 '22 ',
 '4814 ',
 '698 ',
 '13 ',
 '10 ',
 '59 ',
 '56 ',
 '482 ',
 '171 ',
 '5 ',
 '500 ',
 '411 ',
 '8519 ',
 '21 ',
 '21 ',
 '171 ',
 '7 ',
 '49 ',
 '12 ',
 '3 ',
 '21 ',
 '9 ',
 '8 ',
 '7 ',
 '2 ',
 '11 ',
 '11 ',
 '173 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 ' ',
 '18 ',
 '21000 ',
 '115 ',
 '21 ',
 '206 ',
 '43680 ',
 '8 ',
 '10 ',
 '59 ',
 '10 ',
 '5 ',
 '5 ',
 '1000 ',
 '138 ',
 ' ',
 '16 ',
 '2 ',
 '10 ',
 ' ',
 '8 ',
 '6 ',
 '129 ',
 '81 ',
 '12 ',
 '6 ',
 '22 ',
 '18 ',
 '9 ',
 '754 ',
 '14 ',
 '5 ',
 ' ',
 ' ',
 '18 ',
 '7 ',
 '7 ',
 ' ',
 '7 ',
 '5 ',
 '6 ',
 '4 ',
 '18 ',
 '11 ',
 '25 ',
 ' ',
 '20 ',
 '12 ',
 '46 ',
 '9 ',
 '8 ',
 '49 ',
 '11 ',
 '8 ',
 '54 ',
 '36 ',
 '3916 ',
 '710 ',
 '18 ',
 '8 ',
 '29 ',
 '7 ',
 '9 ',
 '37 ',
 '6 ',
 '1024 ',
 '1024 ',
 '14 ',
 '7 ',
 '8265 ',
 '29 ',
 '25 ',
 '3 ',
 '115 ',
 '1 ',
 '12 ',
 '13 ',
 '200000 ',
 '6 ',
 '21 ',
 '4 ',
 '2400 ',
 '175 ',
 '10 ',
 '4714 ',
 '23 ',
 '17 ',
 '2 ',
 '9 ',
 '8 ',
 '280 ',
 '49 ',
 '3 ',
 '14 ',
 '19 ',
 ' ',
 '54 ',
 '8 ',
 '1087 ',
 '12 ',
 '3 ',
 '17 ',
 '8 ',
 '9 ',
 '12 ',
 '1656 ',
 '6 ',
 '2 ',
 '11 ',
 '533 ',
 '14 ',
 '84 ',
 '22 ',
 '16 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '13 ',
 '13 ',
 '55 ',
 '39 ',
 '4 ',
 '7 ',
 '79 ',
 '1 ',
 ' ',
 '14 ',
 '96 ',
 '21 ',
 ' ',
 '5 ',
 '2 ',
 '69 ',
 '9 ',
 '124 ',
 '20 ',
 '25 ',
 '11 ',
 '19 ',
 '9 ',
 '9 ',
 '5 ',
 '7 ',
 '4006 ',
 '2 ',
 '19 ',
 '4 ',
 '13 ',
 '55 ',
 '1 ',
 '7842 ',
 '15 ',
 '15 ',
 '70 ',
 '7842 ',
 '4 ',
 '14 ',
 '17 ',
 '23 ',
 '321 ',
 '1068 ',
 '1068 ',
 '5 ']

In [56]:
# scraping year
year=[i.text for i in driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[7]")]
year=year[1:]
year

['1995 ',
 '1996 ',
 ' ',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ',
 '1994 ',
 '1994 ',
 ' ',
 '1988 ',
 '1992 ',
 '1995 ',
 '1995 ',
 '1990 ',
 '1997 ',
 '1996 ',
 '1988 ',
 '1989 ',
 '1994 ',
 ' ',
 ' ',
 '1995 ',
 ' ',
 '1992 ',
 '1987 ',
 '1997 ',
 '1998 ',
 '1995 ',
 '1998 ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1989 ',
 '1996 ',
 '1990 ',
 '1990 ',
 '1987 ',
 '1999 ',
 '1989 ',
 '1988 ',
 '1988 ',
 '1989 ',
 ' ',
 '1990 ',
 '1998 ',
 '1989 ',
 '1988 ',
 '1994 ',
 '1990 ',
 '1988 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '1990 ',
 ' ',
 '1992 ',
 '1988 ',
 '1990 ',
 '1996 ',
 '1995 ',
 '1990 ',
 ' ',
 '1992 ',
 '1992 ',
 '1994 ',
 ' ',
 '1987 ',
 '1994 ',
 '1994 ',
 '1997 ',
 '1991 ',
 '1995 ',
 '1998 ',
 '1998 ',
 '1993 ',
 '1988 ',
 ' ',
 ' ',
 '1992 ',
 '1993 ',
 '1988 ',
 '1989 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1999 ',
 '2001 ',
 '2001 ',
 ' ',
 '1992 ',
 '1993 ',
 '1997 ',
 '1991 ',
 '1987 ',
 '1994 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1988 ',
 '1991 ',
 '1996 ',
 '1990 ',
 ' ',
 '1999 ',
 '1999 ',
 '2002 ',
 ' ',
 '2000 ',
 '1999 ',
 '1999 ',
 '2001 ',
 '1999 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '1999 ',
 ' ',
 '1998 ',
 '1999 ',
 '2001 ',
 '1999 ',
 ' ',
 '2003 ',
 '1999 ',
 '1999 ',
 '1997 ',
 '1999 ',
 '1999 ',
 '1998 ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1993 ',
 '1990 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1989 ',
 '2006 ',
 '2006 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2010 ',
 '2009 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ',
 '2021 ']

In [57]:
# putting into dataframe
df=pd.DataFrame({'Name':name,'Data Type':data_type,'Dafault Task':default_task,'Attribute Types':attribute_type,'Instance':instance,'Attribute':attributes,'Year':year})
df

,Name,Data Type,Dafault Task,Attribute Types,Instance,Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021